---
title: John Daniel for Rally Commissioner
author: the John Daniel Election Committee
email: contact@norombabajd.com
description: John Daniel is on a mission to be Frontier's Rally Commissioner (again).
baseurl: "/"
url: https://votejohndaniel.com
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
