---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: index.md
  label: index.md
- type: document
  path: campaign.md
  label: campaign.md
- type: document
  path: profile.md
  label: profile.md
- type: heading
  label: Settings
- type: document
  path: _config.yml
  label: _config.yml
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --config _config.yml,_config_staging.yml
    --drafts --unpublished --future --port 8080 --host 0.0.0.0 -d _site
